# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OlineNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('textdata', models.DateTimeField()),
                ('author', models.CharField(max_length=50)),
                ('mainbody', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OlineProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('textdata', models.DateTimeField()),
                ('author', models.CharField(max_length=50)),
                ('projectabstract', models.TextField()),
                ('projectweb', models.TextField()),
            ],
        ),
    ]
